name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case repository name
        run: |
          REPO_NAME="${{ github.repository }}"
          REPO_NAME_LC="${REPO_NAME,,}"
          echo "REPO_NAME_LC=${REPO_NAME_LC}" >> $GITHUB_ENV
          
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME_LC }}/python/flask-app:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME_LC }}/python/flask-app:latest
